spring:
    datasource:
        url: jdbc:h2:mem:database;DB_CLOSE_DELAY=-1
        username: sa
        password: sa
        driver-class-name: org.h2.Driver
    jpa:
        properties:
            hibernate:
                archive.autodetection: class
                jdbc.lob.non_contextual_creation: true
                dialect: org.hibernate.dialect.H2Dialect
                show-sql : true
        hibernate:
            ddl-auto: create
